service: api
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  api-app:
    handler: handler.serverHandler
    events:
      - http: 
          path: /
          method: GET
          cors: true
      -http: 
          path: /{proxy+}
          method: ANY
          cors: true
